name: "Deploy to Gradle Plugin Portal"
# Publish the plugin when a GitHub release is published
on:
  release:
    types: [published]
jobs:
  # End-to-end test: performs a real upload to Sonatype Central with the test artifacts
  e2e:
    name: "End-to-end Test"
    runs-on: ubuntu-latest
    environment: "Gradle Plugin Test"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Run Functional Tests
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./gradlew functionalTest --no-daemon
  deploy:
    name: "Deploy Gradle Plugin"
    needs: e2e
    runs-on: ubuntu-latest
    environment: "Gradle Plugin Portal"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Publish Plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew --no-daemon publishPlugins
