name: "Deploy to Gradle Plugin Portal"
# Only execute this workflow when a PR is opened or when something is pushed to the master branch
on:
  release:
    types: [published]
jobs:
  deploy:
    name: "Deploy Gradle Plugin"
    # Set up OS
    runs-on: ubuntu-latest
    environment: "Gradle Plugin Portal"
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4
      # Setup java and maven
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: 'gradle'
      # Setup executable gradle
      - name: Make Gradle executable
        run: chmod +x gradlew
      # Test plugin
      - name: Publish Plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew --no-daemon publishPlugins